### ISSUE TITLE
www 라이브러리 설치 관련

### ISSUE THREAD

**Issue by eunohhh** [leesum-in/pagebrothers#18]
### 1) tailwind-merge
- clsx 와 비슷하게 사용할 수 있고, className 충돌 문제도 해결해줍니다.
- 예를들어 아래와 같이 사용할 수 있습니다.
- 번들사이즈가 증가하긴 하지만 필요할 때 매우 요긴하게 사용할 수 있어서 사용 건의합니다~!
```tsx
<div className={twMerge("px-2, isWide && "px-1")}></div>
```
[참고링크](https://xionwcfm.tistory.com/322)

### 2) svgr
- svg를 react 컴포넌트처럼 사용할 수 있습니다.
- svg사용이 매우 편리해지므로 사용 건의합니다~!

**Comment by YISYISYISYIS** [comment]
- tailwind-merge : 클래스 이름 충돌도 해결해주고 , clsx기능도 품고 있어서  유용한거같습니다!

- svgr : svg파일을 컴포넌트처럼 쓸수있다는 점이 마음에 듭니다 좋아요!

**Comment by ZiiYOU** [comment]
**1) tailwind-merge**
tailwind css 와 atomic 디자인 기반인 저희 프로젝트에 사용하기에 유용한 라이브러리이네요 🤔🤔

**2) svgr**
컴포넌트 방식으로 사이즈 색상 등을 지정하고 사용할 수 있어서 이 라이브러리 또한 찬성입니닷 👍🏻
