### ISSUE TITLE
[버그]Prettier 포맷팅 오류 (LF and CRLF)

### ISSUE THREAD

**Issue by YISYISYISYIS** [leesum-in/pagebrothers#22]
### 문제 상황
- Prettier는 기본적으로 LF(Unix 스타일의 줄바꿈 Mac)를 사용
- CRLF(Windows 스타일 줄바꿈)이 있으면 오류가 발생
- 그전까지 인지 못하던중, 깃클론 받고 작업중에 문제발생함
![화면 캡처 2024-09-16 220254](https://github.com/user-attachments/assets/3eb53b30-c403-4165-8994-cc1235774899)

<br>

### 해결방안
- 루트레벨 .prettierrc 에 하단 내용 추가후
```
{
  "endOfLine": "lf"
}
```
- Prettier로 전체 파일 포맷팅
`pnpm prettier --write .`

<br>

### 현재 상황
- 빌드시 오류 없음
- 12개의 파일에서 LF관련 포멧팅 된듯?
- Prettier 규칙을 비활성화라던지 .gitattributes파일에 명령어 추가해주는 법 등 추가로 해줄 수 있는 법은 찾아보기만함

**Comment by eunohhh** [comment]
저도 만났던 문제인데 "endOfLine" : "auto" 로 일단 막았었네요.
LF로 하면 되나봐요~ 확인했습니다.

**Comment by YISYISYISYIS** [comment]
- 강제적이긴 한데 "lf"고정으로 한 이유는
1. 대부분의 서버 환경(Linux, macOS 등)에서는 LF를 표준으로 사용
2. Git도 기본적으로 LF를 선호
3. LF는 Unix 계열뿐만 아니라 Windows에서도 잘 작동하지만, CRLF는 Unix 계열 시스템에서 문제가 발생할 수있음

- 결론
고로 괜히 여기에 시간낭비하지말고 lf로 맘편히 고정 시키고 출발하면 좋을 거 같아서 입니다.
