### ISSUE TITLE
[Q&A] storybook UI -> Controls 동기화 되지 않는 문제

### ISSUE THREAD

**Issue by iamheroine** [leesum-in/pagebrothers#32]
### Discussed in https://github.com/leesum-in/pagebrothers/discussions/31

<div type='discussions-op-text'>

<sup>Originally posted by **iamheroine** September 23, 2024</sup>
<img width="897" alt="image" src="https://github.com/user-attachments/assets/21e9f96e-b2ff-462e-aeb0-ad5841466fe9">

금일 회의에서 확인된 storybook Controls & UI 동기화 문제(_하단의 Controls에서 boolean 값 수기로 선택해서 제어 시 UI에 반영되지 않았던 문제_)는 storybook이 비제어 컴포넌트로 되어 있어서 반영이 되지 않았던 부분이라 수정하여 해결했습니다.

그런데 이번에는 UI에서 체크박스를 클릭하는 등의 제어를 하면 하단의 Controls에는 boolean 값이 반영되지 않는 것을 확인했습니다.
결론은, stylebook을 사용하지 못하는 것이 아닌 사소한 문제라 추가적인 수정은 하지 않으려고 합니다.

그 전에 팀원분들이 만드신 컴포넌트와 스타일북은 이러한 문제가 없거나 해결 방법을 알고 계시다면 공유를 부탁드리고자 올립니다🙏🏻</div>

**Comment by YISYISYISYIS** [comment]
![2024-09-2410-26-45-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/7eab22ef-b287-4fd4-b664-6ecb6db77a01)

수정해본 코드입니다.
```
import { useArgs } from '@storybook/addons';
...
const Template: StoryFn<typeof Checkbox> = (args) => {
  const [isChecked, setIsChecked] = useArgs();

  const handleCheckChange = useCallback(
    (checked: boolean) => {
      setIsChecked({ checked }); 
      args.onChange?.(checked);
    },
    [setIsChecked, args],
  );

  return <Checkbox {...args} checked={isChecked.checked} onChange={handleCheckChange} />;
};
```
 useArgs라는 스토리북에서 제공하는 훅이있는데요, Storybook의 args와 상태를 동기화할 수 있는 훅입니다.
 useArg가 args와 직접적으로 연결되면서 useState로 관리하던 부분을  삭제했습니다.
 setIsChecked({ checked }) 이런식으로 useArgs훅을 통해 상태를 업데이트하는경우 객체상태로 전달해야 한다고 하네요
 
 apps/storybook 위치에서
 `pnpm add @storybook/addons` 설치해줬습니다.

**Comment by iamheroine** [comment]
와우 감사합니다! storybook에서 제공하는 훅을 사용하면 상태를 쉽게 동기화 시킬 수 있는 방법이 있었군요🧐
게다가 코드가 더 짧아져서 좋네요! useArgs를 사용해서 수정해봐야겠습니다.
