### ISSUE TITLE
[라이브러리] @dnd-kit 사용 관련

### ISSUE THREAD

**Issue by eunohhh** [leesum-in/pagebrothers#39]
## @dnd-kit
- 문제 : 위젯을 구현하기 위해 dev.pagesister.cc 를 보니 드래그앤드랍 구현이 필수였습니다.
- 분석 : 라이브러리 or 직접구현 인지 확인해보다가 마크업에서 aria-describedby="DndDescribedBy-0" 이런 부분을 봐서 검색해봤습니다.
- 결과 : @dnd-kit 이라는 라이브러리를 쓰신것으로 일단 판단했습니다.
- 제안 : 그래서 저희도 이 라이브러리를 쓰는 것이 어떨지 제안드립니다.

## gpt 의 답변 첨부

제공해주신 마크업에서 `aria-describedby="DndDescribedBy-0"`라는 속성이 있는 것을 보았습니다. 이 속성과 함께 `aria-roledescription="sortable"` 등이 사용된 것으로 보아, 해당 사이트는 **@dnd-kit** 라이브러리를 사용했을 가능성이 높습니다.

**이유 설명:**

- **@dnd-kit의 접근성(A11y) 구현 방식**: @dnd-kit 라이브러리는 접근성을 위해 ARIA 속성을 적극적으로 활용합니다. 특히 드래그 앤 드롭 아이템에 대해 `aria-describedby` 속성을 사용하여 보조 기술이 요소를 올바르게 해석하도록 돕습니다.
  
- **`DndDescribedBy-` 패턴**: `aria-describedby`의 값으로 `DndDescribedBy-0`, `DndDescribedBy-1`와 같은 ID를 사용하는 것은 @dnd-kit 라이브러리에서 일반적으로 나타나는 패턴입니다. 이는 드래그 가능한 요소들을 유일하게 식별하기 위해 자동으로 생성되는 ID입니다.

- **`aria-roledescription="sortable"`**: 이 속성은 해당 요소가 정렬 가능한(sortaable) 리스트의 아이템임을 나타냅니다. @dnd-kit은 이러한 ARIA 속성을 통해 사용자에게 추가적인 컨텍스트를 제공합니다.

**추가 확인 방법:**

1. **개발자 도구에서 스크립트 확인**: 페이지의 소스나 네트워크 탭을 확인하여 `@dnd-kit` 관련 스크립트가 로드되고 있는지 확인합니다.

2. **React 컴포넌트 구조 확인**: @dnd-kit은 React 라이브러리이므로, 해당 사이트가 React로 구축되어 있는지 확인합니다. React 컴포넌트의 클래스나 함수명이 `useDraggable`, `useDroppable` 등과 같이 @dnd-kit의 API와 유사하다면 사용하고 있을 가능성이 높습니다.

3. **CSS 클래스명 확인**: @dnd-kit에서 기본적으로 제공하는 클래스명이나 데이터 속성이 있는지 확인해 볼 수 있습니다.

**결론:**

마크업에 나타난 ARIA 속성과 그 값들을 고려했을 때, 해당 사이트는 **@dnd-kit** 라이브러리를 사용하여 드래그 앤 드롭 기능을 구현한 것으로 보입니다. 따라서 @dnd-kit을 참고하여 드래그 앤 드롭 기능을 구현하시면 유사한 결과를 얻을 수 있을 것입니다.

**도움이 될 만한 자료:**

- **@dnd-kit 공식 문서**: [https://docs.dndkit.com/](https://docs.dndkit.com/)
- **접근성 고려사항**: 드래그 앤 드롭 구현 시 ARIA 속성 사용 방법과 보조 기술 지원에 대한 내용을 참고하세요.

**Comment by YISYISYISYIS** [comment]
저는 react-dnd 사용했었는데 이게 되게 구닥다리 라이브러리였네요 😢

검색해보니 최근에 나와서 사용하기도 쉽다네요. 저도 이게 괜찮을거같습니다!

다른분들 혹시 드래그앤드랍관련 라이브러리 사용해보셨거나 다른 라이브러리 아시는거 있으시면 추천해주시면 좋을거같네요

**Comment by ZiiYOU** [comment]
전 드래그 앤 드랍을 구현해본 적이 없어서 잘모르지만,, @dnd-kit 라이브러리 좋은 것 같은데요? 🤔

**Comment by iamheroine** [comment]
특정 라이브러리에 내장된 드래그앤드랍 기능 외에는 별도로 설치하여 사용해본적은 없습니다🙃
저도 dnd-kit 괜찮아보입니다.
제가 맡은 위젯 리스트 모달에도 필요한데 빠른 서칭 감사합니다!

🔽 근거 자료
https://dev.to/bryntum/best-drag-and-drop-libraries-for-frontend-developers-39d5
https://npmtrends.com/@dnd-kit/core-vs-react-beautiful-dnd-vs-react-dnd-vs-react-draggable (업데이트 2년 전..)
https://josiah0208.tistory.com/7
https://www.reddit.com/r/reactjs/comments/14w4zrh/which_library_is_good_for_drag_and_drop/ (단편적인 의견들이지만 언급이 제일 많이 됨)

🔽 라이브러리 의사 결정 작성에 참고하면 좋을 것 같은 양식
https://haegomm.tistory.com/entry/troubleshootingtechnology-decisiondrag-and-drop-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EC%84%A0%ED%83%9D

**Comment by YISYISYISYIS** [comment]
근거 자료나 양식으로 제공해주신 정보 너무좋네요! 👍 그래서 개인적으로 경험했던걸 공유드려볼게요.

저는 react-dnd 와 react-beautiful-dnd 를 예전에 기술적의사결정하면서 **react-dnd**선택했는데 
#### 가장 큰 이유
- react-beautiful-dnd는 최근 업데이트가 2020년도임 => 리액트18이후 버전에서 이슈가 있는걸로 파악 => 유저가 커스텀으로 설정부분 수정해주면 사용은 가능 => 꺼림칙함😕
실제 테스트용으로 둘다 받아서 할때 react-dnd는 공식문서 참조후 바로 사용가능 했었고, react-beautiful-dnd는 오류뿜뿜

다른 라이브러리는 테스트를 해보지 않아서 모르겠고 react-beautiful-dnd는 후보에 넣는 다면 저는 선택하지는 않을것 같습니다!
react-dnd는 제가 사용했을때는 잘썼고 **좀더 쉽고** 직관적인 툴이 있다면 저는 그걸 써보고 싶긴해요!

**Comment by eunohhh** [comment]
의사결정 이슈 오픈시 참고할 양식을 공유해주셔서 감사합니다! 
해당 양식처럼 작성하면 좋을 것 같습니다.
저는 요번엔 원본 사이트와 같게 dnd-kit 을 써보면 좋을 것 같습니다 ㅎㅎ
