### ISSUE TITLE
[라이브러리/유틸리티] tailwind-merge와 clsx 결합사용 관련

### ISSUE THREAD

**Issue by eunohhh** [leesum-in/pagebrothers#44]
이 이슈는 내용이 유틸리티 함수에 대한 것이라서 
디스커션에 올려야 하나 하다가, clsx 라이브러리 설치와도 관련되어서 이슈로 올립니다!

## clsx 라이브러리 및 cn 유틸함수
- tailwind-merge 라이브러리 사용은 이미 결정이 되었었는데요. clsx 는 아직 결정이 안된 것 같아요~
- clsx 는 많이 쓰기도 하고 매우 편리해서 같이 쓰면 좋을 것 같습니다!
- 그리고 이 둘을 결합해서 사용하면 매우 유용할 것 같은 유틸리티 함수를 하나 찾았는데요. 아래와 같습니다.

```ts
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
```
- 위 함수는 clsx 의 className 조건부 사용 기능과, tailwind-merge 의 유틸리티 클래스 병합 기능을 동시에 사용할 수 있게 해줍니다.

```ts
const className = cn('p-4', padding && 'p-6', 'text-center', { 'btn-primary': isPrimary, 'btn-disabled': isDisabled });
```
- 이런 식으로요!

### 문제 인식

프로젝트에서 특정 상황에 따라 Tailwind CSS 클래스를 동적으로 적용해야 하는데,
조건부 로직을 처리하면서 중복된 클래스도 제거하면 좋을 것 같습니다. 

### 리서치 / 접근

문제를 해결하기 위해 여러 가지 접근 방식을 고려했습니다:

- **Tailwind CSS만 사용**: 가능하지만 코드가 장황해지고 유지보수성이 떨어짐.
- **`tailwind-merge`**: 중복 클래스 제거는 가능하지만 조건부 클래스를 간결하게 처리하는 기능 부족.
- **`clsx`**: 조건부 클래스를 동적으로 관리할 수 있으나 중복 제거는 별도로 처리해야 함.
- **`clsx` + `tailwind-merge` 결합**: 조건부 클래스 적용과 중복 클래스 제거를 동시에 처리할 수 있음.

## 의사결정

최종적으로 **clsx**와 **tailwind-merge**의 결합을 사용하기로 결정했습니다. `clsx`는 조건부 클래스를 간결하게 적용할 수 있고, `tailwind-merge`는 중복된 Tailwind 클래스를 제거할 수 있어, 두 라이브러리를 함께 사용하면 문제를 효과적으로 해결할 수 있습니다.

이 결정을 통해 코드의 **가독성**과 **유연성**이 향상될 것으로 기대됩니다.

[참고링크-cn](https://tigerabrodi.blog/the-story-behind-tailwinds-cn-function)
[참고링크-블로그정리](https://ifelseif.tistory.com/215#%EC%98%88%EC%8B%9C%3A-1)

**Comment by iamheroine** [comment]
저도 cn 함수를 이전에 사용해본 경험이 있는데요!
처음에는 두 라이브러리 모두 Tailwind CSS를 사용하면서 클래스명을 동적으로 조합하거나, 불필요한 클래스 중복을 제거해주는 공통점이 있어서 하나만 설치해서 사용해도 괜찮지 않을까 생각했습니다.
그런데 클래스 동적 처리, 조건부 로직을 처리, 클래스 중복 제거에 clsx와 tailwind merge의 조합의 효율이 좋은 것을 경험했기 때문에 다음 프로젝트에 tailwind를 사용한다면 다시 사용하고 싶은 생각이 있었는데 찬성입니다👍

**Comment by YISYISYISYIS** [comment]
오호 또 뭔가 새로운것이군요!
사실 저는 여전히 템프릿리터럴 사용하는 구닥다리방식이 편합니다.
아직까지 여러 조건이 복잡하게 얽힌 코드를 짠적이 없다보니 불편함을 느낀적이 없어서 그런거 같아요
그런데 사용하게되면 가독성은 확실히 좋아질것 같은데요!

- 그래서 여기서 질문인데요❔
이거 쓰기로 정해지면  무조건 쓰는거죠? 유예기간 있나요?

**Comment by eunohhh** [comment]
cn 도 그냥 템플릿리터럴 넘기는 방식으로 써도 괜찮아요 ㅎㅎ
그냥 clsx(`어쩌구`), twMerge(`어쩌구`) 대신에 cn(`어쩌구`) 쓰시면 될 것 같아요 ㅋㅋ

무조건 쓰지 않아도 될 것 같아요! 필요할 때 쓰면 될듯요~~
