### ISSUE TITLE
[라이브러리] uuid 사용 제안

### ISSUE THREAD

**Issue by eunohhh** [leesum-in/pagebrothers#60]
## @uuid / @types/uuid
- Problem : 청첩장 useMutation 할 경우에 uuid 필요한 것 같습니다.
- Research : 음...이 경우는 대체제가 없는것 같습니다. 거의 uuid 가 유일한 선택지 같습니다.
- Decision : 그래서 설치했습니다~~~!

**Comment by YISYISYISYIS** [comment]
좋아요!

근데 궁금한게 예전에 교육할때 크립토? 내장돼있는 기능 배운기억이 있는데 이건 별론가요?

사실 개인프로젝트할때 uuid깔기 귀찮아서 크립토 썼었거든요? 잘 돌아가길래 왜 굳이 라이브러리 설치해서쓰지? 생각을 해본적이있거든요

약간 컨텍스트api같은 느낌인건가,, 상황에 따라서 선택하는? 🤔

**Comment by eunohhh** [comment]
저 그거 몰랐습니다!!
Crypto.randomUUID() 가 더 좋은것 같아요!!

**Comment by eunohhh** [comment]
crypto.randomUUID() 사용으로 결정되었습니다~!
