### ISSUE TITLE
cn import 경로 관련 Issue

### ISSUE THREAD

**Issue by ZiiYOU** [leesum-in/pagebrothers#62]
## 📌 Issue의 주된 내용

cn import 경로가 절대경로로 설정될 경우 경로 인식이 안됩니다.

## 🧐 Issue를 해결하기 위한 과정

현재 제가 올린 ' 빌드 에러 해결' PR 에서 이 문제를 해결하기 위해, import 시 '@' 를 사용할 수 있도록 tsconfig 파일에 해당 코드를 추가해주었습니다.
```tsx
"paths": {
      "@/*": ["./src/*"], // 추가된 부분
      "*.svg": ["./svg.d.ts"]
    },
```
또한, cn 함수를 export default 로 변경해주었고 이에 따라 index.ts 에서도 코드 수정해주었습니다.

제가 올린 PR 기준으로 cn 을 자동 import 해올 경우,
```tsx
import { cn } from '@/utils'
```
이런 형태로 경로가 형성되지만 이 경로를 인식하지 못합니다.
이외에도 index.ts 파일들을 확인해봤지만 특별히 문제가 될 부분은 확인하지 못했습니다.

혹시 이 Issue 관련해서 아이디어가 있으신 분 계실까요~?

**Comment by eunohhh** [comment]
저도 만났던 에러인데요!
shared 자체 에는 react 나 next 가 설치되어 있지 않기때문에
webpack 이나 babel 같은 빌드 도구가 없고, 그래서 shared 내부에서의 실시간 상호 참조시에는(pnpm dev 중일때)
` import { cn } from '@/utils' ` 로는 참조가 안되는 것으로 확인했습니다.
최초에 모노레포 세팅시에는 shared 에서 매번 build 후 dist에서 참조하여 쓰는 것으로 되어 있었던 것도 아마 이런 문제 때문인것 같습니다.

다른 경로(apps/www 라거나..)에서 `@repo/shared` 같은식으로 참조가 되는 것은
전체 모노레포를 터보레포가 돌려(?) 주기 때문에 가능한 것 같습니다.

그래서 제 생각에 이 문제는 그냥 shared 내부에서의 상호 참조시 ../../ 상대경로를 쓰는 것으로 해야 할 것 같다는 의견입니다!

**Comment by ZiiYOU** [comment]
넵 확인했습니다 !
답변 감사합니다.

**Comment by iamheroine** [comment]
이 부분 회의 때 말씀해주셨는데 수정을 하지 않았네요ㅠㅠ 인지하고 사용하겠습니다!
