### ISSUE TITLE
[라이브러리] @vis.gl/react-google-maps 설치 관련

### ISSUE THREAD

**Issue by eunohhh** [leesum-in/pagebrothers#76]
📌 인트로 위젯 > 장소 검색(구글)시 Google Maps Autocomplete 기능 구현을 위한 패키지 설치 및 선택 이유

📋 설치한 패키지
  - `1)`  @types/google.maps (^3.58.1)
    - 설치 이유: TypeScript 프로젝트에서 google.maps 객체에 대한 타입 정의를 제공하기 위해 설치했습니다. 이는 타입 지원을 위해 필수적인 패키지로, 특별한 의사결정 없이 추가했습니다.
  - `2)` @vis.gl/react-google-maps (^1.3.0)
    - 설치 이유: Google의 공식 문서에서 React와 Google Maps를 통합할 때 이 패키지를 권장하고 있어 사용했습니다.

🔍 패키지 선택 과정 및 이유
  - npm에서 React와 관련된 여러 Google Maps 라이브러리를 조사했습니다.
  - 하지만 대부분 문서화가 부족하거나 커뮤니티 지원이 미흡했고, 유지보수가 미흡했습니다.
  - @vis.gl/react-google-maps 선택 이유:
    - 공식: Google의 공식 문서에 소개되어 있어 신뢰성이 높다고 판단했습니다.
    - 유지보수성: 공식적으로 지원되는 패키지이므로 업데이트 및 유지보수가 꾸준히 이루어질 것으로 기대됩니다.
    - 문서화 및 지원: 공식 문서를 통해 충분한 가이드와 지원을 받을 수 있습니다.

📚 참고 링크
  - [Google Maps Platform 공식 문서 - React 통합 가이드](https://developers.google.com/maps/documentation/javascript/react-map)
  - [React Google Maps Library - Place Autocomplete](https://developers.google.com/maps/documentation/javascript/examples/rgm-autocomplete)

**Comment by ZiiYOU** [comment]
@vis.gl/react-google-maps 설치와 관련해서 의사결정 과정 정리 및 참고 링크 전달 감사드립니다 👍🏻
공식적으로 지원되는 라이브러리를 사용하는 것이 여러 측면에서 좋은 생각인 것 같아요 !

**Comment by YISYISYISYIS** [comment]
공식지원이 가장 좋은 선택으로 보이네요! 

기능적이나 성능적으로 개선이 필요할 경우는 추후에 다시 살펴보면 될거 같습니다
