### ISSUE TITLE
[라이브러리] react-datepicker 및 date-fns 사용 관련

### ISSUE THREAD

**Issue by eunohhh** [leesum-in/pagebrothers#80]
📌 인트로 위젯 > 달력 기능 구현을 위한 패키지 설치 및 선택 이유

📋 설치한 패키지
1. react-datepicker (^7.5.0)
2. date-fns (^4.1.0)

🔍 패키지 선택 과정 및 이유
1. react-datepicker 설치 이유
- 기존 프로젝트에서 사용 중인 달력 컴포넌트로, 동일한 UI를 유지하기 위해 react-datepicker를 선택했습니다. 
- 이 패키지를 사용하면 UI 통일성을 확보할 수 있고, 추가적인 학습 부담 없이 바로 적용할 수 있습니다.
2. date-fns 설치 이유
- 날짜와 시간을 처리하기 위한 유틸리티로 date-fns를 선택했습니다. dayjs나 moment와 비교했을 때, 다음과 같은 장점이 있어 date-fns를 우선 고려하게 되었습니다:
- 유용한 기능: isBefore, startOfDay 등 유용한 기능들이 많습니다.
- 트리쉐이킹: 모듈화가 잘 되어 있어서, 필요한 기능만 불러올 수 있어 번들 크기를 줄일 수 있습니다.
- 타입스크립트 지원: date-fns는 TypeScript와 잘 호환되어 타입 안전성을 높일 수 있습니다.

📚 참고 링크
[react-datepicker GitHub](https://github.com/Hacker0x01/react-datepicker)
[date-fns GitHub](https://github.com/date-fns/date-fns)

**Comment by YISYISYISYIS** [comment]
기존 UI와 통일성이나 번들크기라던지 호환성 관련해서도 합리적인 선택인거 같네요!
