### ISSUE TITLE
[라이브러리] dnd-kit 관련 추가 라이브러리 설치 

### ISSUE THREAD

**Issue by eunohhh** [leesum-in/pagebrothers#88]
### 📌 드래그 앤 드롭 정렬 기능 구현을 위한 패키지 설치 및 선택 이유

dnd-kit 을 활용해 드래그앤드랍시 index가 변경된다거나 하는 경우에필수적인 추가 라이브러리가 @dnd-kit/sortable 였습니다.
그리고 @dnd-kit/utilities 는 이름 그대로 여러가지 계산을 해주는 라이브러리여서 역시 필수적이라 설치했습니다.

shared 등 전역적으로 사용할일이 꼭 있을 것 같아 전역으로 설치했습니다.
(추가로 스토리북 이슈도 있었으므로)

제가 어설프게 설명하는 것보다 GPT 가 더 정확한 의사결정 참고사항을 제공해주어서 아래 첨부합니다!

---

### 📋 설치한 패키지

- **@dnd-kit/core (^6.2.0)**
- **@dnd-kit/sortable (^9.0.0)**
- **@dnd-kit/utilities (^3.2.2)**

---

#### **1. @dnd-kit/core 설치 이유**
`@dnd-kit/core`는 드래그 앤 드롭(DnD) 기능을 제공하는 React 기반의 핵심 라이브러리입니다.  
다양한 요구사항에 따라 커스터마이징할 수 있는 유연성과 성능 면에서 뛰어나 선택했습니다.

- **React 친화적**: React의 상태와 구조에 최적화되어 있어, 기존 프로젝트에 쉽게 통합할 수 있습니다.
- **모던 아키텍처**: DOM 요소 대신 **가상 드래그 객체**를 사용하여 성능이 뛰어나고, 브라우저 호환성이 우수합니다.
- **유연성**: 커스터마이징 가능한 API를 제공하여 복잡한 드래그 앤 드롭 동작도 구현이 가능합니다.

---

#### **2. @dnd-kit/sortable 설치 이유**
`@dnd-kit/sortable`는 `@dnd-kit/core`를 기반으로 정렬 기능을 구현하기 위한 확장 패키지입니다.  
리스트나 그리드 요소를 드래그 앤 드롭으로 정렬할 수 있도록 지원합니다.

- **정렬 기능 제공**: 리스트나 카드 정렬 같은 기능을 쉽게 구현할 수 있습니다.
- **애니메이션 지원**: 이동 시 자연스러운 전환 효과를 기본 제공하여 사용자 경험(UX)을 향상시킬 수 있습니다.
- **자동 충돌 감지**: 드래그 대상이 충돌 영역에 들어왔을 때 자동으로 위치를 계산해줍니다.

---

#### **3. @dnd-kit/utilities 설치 이유**
`@dnd-kit/utilities`는 드래그 앤 드롭 구현 시 필요한 유틸리티 함수를 제공하는 패키지입니다.

- **공통 유틸리티 제공**: 예를 들어, 요소 위치 계산, 충돌 감지, 좌표 변환 등 다양한 공통 작업을 단순화합니다.
- **커스터마이징 용이**: 기본 동작을 오버라이드하거나 세부 동작을 조정하기 위해 필수적인 도구입니다.

---

### 🔑 선택 이유 정리

1. **유연성과 커스터마이징**:  
   - `@dnd-kit`은 React 친화적이고 고도로 커스터마이징 가능한 API를 제공하여 프로젝트 요구사항에 맞춘 드래그 앤 드롭 기능을 구현할 수 있습니다.

2. **모듈화된 구성**:  
   - 핵심 기능(`@dnd-kit/core`)과 정렬 확장(`@dnd-kit/sortable`), 그리고 유틸리티(`@dnd-kit/utilities`)가 분리되어 필요한 기능만 설치하고 관리할 수 있습니다.

3. **경량화 및 퍼포먼스**:  
   - DOM 대신 가상 객체를 사용하여 빠른 성능을 보장하며, 트리쉐이킹(Tree Shaking)을 지원해 번들 크기를 줄일 수 있습니다.

4. **생산성 향상**:  
   - 애니메이션, 충돌 감지 등 다양한 기본 제공 기능 덕분에 코드 작성 시간을 절약할 수 있습니다.

---

### 📚 참고 링크

[@dnd-kit/core GitHub](https://github.com/clauderic/dnd-kit/tree/master/packages/core)
[@dnd-kit/sortable GitHub](https://github.com/clauderic/dnd-kit/tree/master/packages/sortable)
[@dnd-kit/utilities GitHub](https://github.com/clauderic/dnd-kit/tree/master/packages/utilities)

**Comment by YISYISYISYIS** [comment]
클릭과 드래그앤드랍을 동시에 적용하는건 라이브러리가 필수군요!
